name: builder

on:
  schedule:
    - cron: '0 1 7,14,21,28 1-12 ?'
  push:
    paths:
    - '.github/workflows/builder.yml'
    - 'Userge'
    - 'Megasdk'
    - 'Daisyxmusic'
    branches:
    - 'master'

jobs:
  userge:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip userge]')"
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: docker/login-action@v1.9.0
      with:
        username: rzlamrr
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build & Push
      run: |
        docker build . --rm --force-rm --compress --no-cache=true --pull \
        --file Userge --tag rzlamrr/userge:latest
        docker push rzlamrr/userge:latest

  megasdk:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip megasdk]')"
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: docker/login-action@v1.9.0
      with:
        username: rzlamrr
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build & Push
      run: |
        docker build . --rm --force-rm --compress --no-cache=true --pull \
        --file Megasdk --tag rzlamrr/megasdk:latest
        docker push rzlamrr/megasdk:latest

  music:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip music]')"
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: docker/login-action@v1.9.0
      with:
        username: rzlamrr
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build & Push
      run: |
        docker build . --rm --force-rm --compress --no-cache=true --pull \
        --file Daisyxmusic --tag rzlamrr/music:latest
        docker push rzlamrr/music:latest
